Repository MIT-Emerging-Talent/2024-group-02-collaboration-practice, pull requests merged in 2024-01, with the labels that each got.

#26 Update fib.py
  src/dynamic_programming/python/fibonacci/src/fib.py
Labels: bug, invalid

#33 Denys update communication, constraints, learning_goals
  group_study/communication.md
  group_study/constraints.md
  group_study/learning_goals.md
Labels: documentation

#25 Array_product
  src/brain_teasers/python/array_product/README.md
  src/brain_teasers/python/array_product/src/array_product.py
  src/brain_teasers/python/array_product/tests/test_array_product.py
Labels: Challenge, Python
